  206  lua test.lua
  207  lua test.lua
  208  lua test.lua
  209  lua test.lua
  210  lua test.lua
  211  lua test.lua
  212  lua test.lua
  213  lua test.lua
  214  lua test.lua
  215  lua test.lua
  216  lua test.lua
  217  lua test.lua
  218  lua test.lua
  219  lua test.lua
  220  lua test.lua
  221  dd[A
  222  lua test.lua
  223  lua test.lua
  224  lua test.lua
  225  lua test.lua
  226  lua test.lua
  227  lua test.lua
  228  lua test.lua
  229  lua test.lua
  230  lua test.lua
  231  lua test.lua
  232  lua test.lua
  233  lua test.lua
  234  lua test.lua
  235  lua test.lua
  236  lua test.lua
  237  lua test.lua
  238  lua test.lua
  239  gp
  240  git pull
  241  open docs/test.html 
  242  docco -h
  243  docco -h
  244  h | grep dic
  245  h | grep doc
  246  docco --css ~/gits/timm/keys/etc/docco.css test.lua
  247  open docs/test.html 
  248  docco --css $HOME/gits/timm/keys/etc/docco.css test.lua
  249  docco --css $HOME/gits/timm/keys/etc/doacco.css test.lua
  250  cat $HOME/gits/timm/keys/etc/docco.css 
  251  docco -c /Users/timm/gits/timm/keys/etc/docco.css test.lua
  252  docco  test.lua; cp ~/gits/timm/keys/etc/docco.css docs/
  253  docco -h
  254  docco  -l classic test.lua; cp ~/gits/timm/keys/etc/docco.css docs/
  255  docco  -l classic test.lua; 
  256  docco  -l classic test.lua
  257  man docco
  258  docco  -h
  259  docco  -l linear  test.lua
  260  docco  -l classic  test.lua
  261  vi test.lua
  262  docco  -l classic  test.lua
  263  docco  -l linear  test.lua
  264  docco   test.lua
  265  docco   test.lua
  266  history
  267  docco  test.lua; cp ~/gits/timm/keys/etc/docco.css docs/
  268  docco  test.lua; cp ~/gits/timm/keys/etc/docco.css docs/
  269  ldoc test.lua
  270  cd doc
  271  ls
  272  open index.html 
  273  cd ..
  274  ldoc test.lua
  275  rm -rf doc
  276  ldoc test.lua
  277  rm -rf doc
  278  docco  test.lua; cp ~/gits/timm/keys/etc/docco.css docs/
  279  gp
  280  doc lib.lua 
  281  ../etc/h
  282  git status
  283  git add etc/* src/*
  284  gp
  285  vi src/about.lua 
  286  gp
  287  ls
  288  git rm _config.yml 
  289  vi README.md 
  290  gp
  291  vi docs/index.md 
  292  git pull
  293  vi docs/index.md 
  294  vi docs/index.md 
  295  gp
  296  vi docs/index.md 
  297  gp
  298  vi docs/index.md 
  299  gp
  300  vi docs/_layouts/default.html 
  301  cd src
  302  ../etc/pretty about.lua 
  303  gp
  304  vi ../docs/about.md 
  305  h
  306  ../etc/pretty about.lua 
  307  vi ../docs/about.md 
  308  vi ../etc/pretty 
  309  ../etc/pretty about.lua 
  310  vi ../docs/about.md 
  311  gp
  312  cd ../docs
  313  open reasons.png 
  314  ls
  315  cp _layouts/reasons.jpeg .
  316  vi _config.yml 
  317  git add *
  318  gp
  319  cat _layouts/
  320  cat _config.yml 
  321  open reasons.jpeg 
  322  vi _config.yml 
  323  gp
  324  git pull
  325  git pill
  326  git pull
  327  vi _config.yml 
  328  vi index.md 
  329  gp
  330  vi ../src/about.lua 
  331  ../etc/doc *.lua
  332  cd ../src
  333  ../etc/doc *.lua
  334  gp
  335  lua sandbox.lua 
  336  vi sandbox.lua 
  337  vi sandbox.lua 
  338  git pull
  339  rm ../docs/sandbox.md 
  340  gp
  341  git rm ../docs/sandbox.md
  342  git pull
  343  gp
  344  mds
  345  git add ../docs/stats.md 
  346  vi ../docs/_layouts/default.html 
  347  gp
  348  vi stats.lua 
  349  mds
  350  vi stats.lua 
  351  mds
  352  cd ..
  353  mkdir .github
  354  mkdir .github/workflows
  355  cd .github/workflows/
  356  vi tests.yml
  357  cd ..
  358  cd ..
  359  ls
  360  git add .github/workflows/tests.yml 
  361  gp
  362  ls -lsat
  363  vi .gitignore
  364  git add .gitignore 
  365  gp
  366  s
  367  vi src/stats.lua 
  368  mds
  369  vi ../docs/_config.yml 
  370  gp
  371  git pull
  372  git pull
  373  vi tiny.lua 
  374  gp
  375  vi ../docs/_config.yml 
  376  gp
  377  vi ../docs/_config.yml 
  378  gp
  379  vi ../docs/_config.yml 
  380  gp
  381  git pull
  382  vi about.lua 
  383  ../etc/doc *.lua
  384  ls
  385  gp
  386  ls
  387  gp
  388  ../etc/doc *.lua; go
  389  ../etc/doc *.lua; gp
  390  ../etc/doc *.lua; go
  391  gp
  392  ../etc/doc *.lua; go
  393  ../etc/doc *.lua; go
  394  ../etc/doc *.lua; go
  395  gp
  396  ../etc/doc *.lua; go
  397  ../etc/doc *.lua; gp
  398  e sa[A
  399  ../etc/doc *.lua; gp
  400  lua
  401  cd 
  402  cd gits/timm/evenless/src/some.lua 
  403  cd gits/timm/evenless/src/ 
  404  grep '.9' *
  405  more sample.lua 
  406  cd
  407  cd rezons
  408  ls
  409  cd src
  410  grep poly *
  411  ../etc/doc *.lua
  412  ../etc/doc *.lua; gp
  413  git add ../docs/meta.md 
  414  git add ../docs/meta.md 
  415  ../etc/doc *.lua; gp
  416  vi some.lua 
  417  ../etc/doc *.lua; gp
  418  vi some.lua 
  419  ../etc/doc *.lua; gp
  420  vi some.lua 
  421  ../etc/doc *.lua; gp
  422  vi sample.lua 
  423  gp
  424  vi sample.lua 
  425  ../etc/doc *.lua; gp
  426  vi sample.lua 
  427  ../etc/doc *.lua; gp
  428  vi some.lua 
  429  git pull
  430  git diff some.lua
  431  rm some.lua
  432  git pull
  433  vi some.lua 
  434  ../etc/h
  435  tmux
  436  1;95;0c
  437  tmux kill-session -a
  438  tmux ls
  439  tmux ls
  440  tmux kill 4
  441  tmux kill-session 4
  442  tmux kill-session -t 4
  443  tmux ls
  444  ..etc/h
  445  ../etc/h
  446  tmux
  447  1;95;0c
  448  vi rogic.pl 
  449  tmux
  450  lua ssl.lua 
  451  lua ssl.lua 
  452  cd
  453  cd tmp
  454  git clone https://github.com/hakank/hakank/tree/master/answer_set_programming
  455  git clone https://github.com/hakank/hakank
  456  cd hakank/
  457  ls
  458  cd answer_set_programming/
  459  wc * | sort -b
  460  wc * | sort -n
  461  cd
  462  ls .tm*
  463  cd tmp
  464  echo $TERM
  465  git clone https://github.com/gpakosz/.tmux.git
  466  cd .tmux
  467  ls
  468  cd
  469  ln -s -f $HOME/tmp/.tmux/.tmux.conf
  470  cp $HOME/tmp/.tmux/.tmux.conf.local .   
  471  vi src/ssl.lua 
  472  gp
  473  cd
  474  cd tmp
  475  vi all
  476  sort all | cut -f 1
  477  sort all | cut -d\ -f 1
  478  sort all | cut -d\   -f 1
  479  sort all | cut -d\   -f 1 |sort
  480  sort all | cut -d\   -f 1 |sort | gawk '{print $0","}'
  481  sort all | cut -d\   -f 1 |sort | gawk '{print $0","}' |pbcopy
  482  cd
  483  cd rezons
  484  cd src
  485  git pull
  486  alias
  487  vi ../etc/md
  488  lua ssl.lua 
  489  vi ssl.lua 
  490  tmux
  491  1;95;0c
  492  tmux ls
  493  tmux kill-sessions
  494  tmux kill-session
  495  tmux us
  496  tmux ls
  497  git pull
  498  vi src/ssl.lua 
  499  tmux
  500  export TERM=xterm-256color
  501  gp
  502  gp
  503  lua hints.lua -do demo1
  504  git pull
  505  lua hints.lua -do demo1
  506  lua hints.lua -do demo1
  507  lua hints.lua -do demo1
  508  lua hints.lua -do demo1
  509  lua hints.lua -do demo1
  510  lua hints.lua -do demo1
  511  lua hints.lua -do demo1
  512  lua hints.lua -do demo1
  513  lua hints.lua -do demo1
  514  lua hints.lua -do demo1
  515  lua hints.lua -do demo1
  516  lua hints.lua -do demo1
  517  gp
  518  lua hints.lua -do demo1
  519  lua hints.lua -s 2  -do demo1
  520  lua hints.lua -s 16  -do demo1
  521  lua hints.lua -s 10  -do demo1
  522  lua hints.lua -s 10  -do demo1
  523  lua hints.lua -s 10  -do demo1 | sort -k 2
  524  lua hints.lua -s 32  -do demo1 | sort -k 2
  525  lua hints.lua -s 4  -do demo1 | sort -k 2
  526  lua hints.lua -s 8  -do demo1 | sort -k 2
  527  lua hints.lua -s 8  -do demo1 | sort -k 2
  528  lua hints.lua -s 8  -do demo1 | sort -k 2
  529  lua hints.lua -s 3  -do demo1 | sort -k 2
  530  lua hints.lua -s 6  -do demo1 | sort -k 2
  531  lua hints.lua -s 4  -do demo1 | sort -k 2
  532  lua hints.lua -s 5  -do demo1 | sort -k 2
  533  lua hints.lua -s 7  -do demo1 | sort -k 2
  534  lua hints.lua -s 5  -do demo1 | sort -k 2
  535  lua hints.lua -s 5  -do demo1 | sort -k 2
  536  lua hints.lua -s 5  -do demo1 | sort -k 2
  537  doc lib.lua 
  538  doc hints.lua 
  539  open ../docs/hints.html 
  540  doc hints.lua 
  541  ls -t
  542  vi things.lua 
  543  grep merge *
  544  vi ibc.lua 
  545  gp
  546  git pull
  547  doc hints.lua 
  548  lua hints.lua -s 5  -do demo1 | sort -k 2
  549  lua hints.lua -s 5  -do demo1 | sort -k 2
  550  lua hints.lua -s 5  -do demo1 | sort -k 2
  551  doc hints.lua 
  552  doc hints.lua 
  553  docco -h
  554  docco -l linear hints.lua 
  555  open docs/hints.html 
  556  git pull
  557  vi hints.lua 
  558  git checkout hints.lua 
  559  vi hints.lua 
  560  lua hints.lua 
  561  lua
  562  doc hints.lua 
  563  doc hints.lua 
  564  doc hints.lua 
  565  doc hints.lua 
  566  doc guess.lua 
  567  cd sandbox/
  568  ls
  569  vi aa.lua
  570  git pull
  571  ls
  572  vi ee.lua 
  573  git pull
  574  cd ..
  575  ./hints.lua 
  576  ./hints.lua -do rankauto
  577  ./hints.lua -do rankauto1
  578  ./hints.lua -do rankauto1 | sort -n -k 5
  579  ./hints.lua -do rankauto | sort -n -k 5
  580  ./hints.lua -do rankauto | sort -n -k 3
  581  ./hints.lua -do rankauto1 | sort -n -k 3
  582  ./hints.lua -do rankauto | sort -n -k 3
  583  ./hints.lua -do rankauto | sort -n -k 4
  584  ./hints.lua -do rankauto | sort -n -k 3
  585  ./hints.lua -do rankpom | sort -n -k 3
  586  ./hints.lua -do rankpom1 | sort -n -k 3
  587  ./hints.lua -do rankpom | sort -n -k 3
  588  ./hints.lua -do rankpom | sort -n -k 3
  589  ./hints.lua -do rankpom | sort -n -k 3
  590  ./hints.lua -do rankpom 
  591  ./hints.lua -do rankpom |less
  592  ./hints.lua -do rankauto|less
  593  ./hints.lua -do rankauto
  594  ./hints.lua -do rankpom | sort -n -k 3
  595  ./hints.lua -do rankpom | sort -n -k 4
  596  ./hints.lua -do rankpom | sort -n -k 5
  597  ./hints.lua -do rankpom1 | sort -n -k 5
  598  ./hints.lua -do rankpom | sort -n -k 5
  599  ./hints.lua -s 20 -do rankpom | sort -n -k 5
  600  ./hints.lua -s 10 -do rankpom | sort -n -k 5
  601  ./hints.lua -s 10 -do rankpom | sort -n -k 5
  602  ./hints.lua -s 5 -do rankpom | sort -n -k 5
  603  ./hints.lua -s 5 -do rankpom | sort -n -k 4
  604  ./hints.lua -s 5 -do rankpom | sort -n -k 3
  605  ./hints.lua -s 5 -do rankpom1 | sort -n -k 3
  606  ./hints.lua -e .25 -do rankpom1 | sort -n -k 3
  607  ./hints.lua -s 10 -do rankpom | sort -n -k 3
  608  ./hints.lua -s 5 -do rankpom | sort -n -k 3
  609  ./hints.lua -s 5 -R .9 -do rankpom | sort -n -k 3
  610  ./hints.lua -F 32 -R .9 -do rankpom1 | sort -n -k 3
  611  ./hints.lua -F 64 -R .9 -do rankpom1 | sort -n -k 3
  612  ./hints.lua -F 128 -R .9 -do rankpom1 | sort -n -k 3
  613  ./hints.lua -F 10 -R .9 -do rankpom1 | sort -n -k 3
  614  ./hints.lua -do rankpom | sort -n -k 3
  615  ./hints.lua -do rankpom1 | sort -n -k 3
  616  ./hints.lua -do rankauto | sort -n -k 3
  617  ./hints.lua -do rankauto | sort -n -k 3
  618  ./hints.lua -do rankauto | sort -n -k 3
  619  ./hints.lua -do rankauto | sort -n -k 3
  620  ./hints.lua -do rankauto1 | sort -n -k 3
  621  ./hints.lua -do rankpom | sort -n -k 3
  622  ./hints.lua -do rankpom | sort -n -k 4
  623  ./hints.lua -do rankpom | sort -n -k 4
  624  ./hints.lua -do rankpom | sort -n -k 4
  625  ./hints.lua -do rankpom | sort -n -k 4
  626  ./hints.lua -do rankpom | sort -n -k 4
  627  ./hints.lua -do rankpom | sort -n -k 3
  628  ./hints.lua -do rankpom1 | sort -n -k 3
  629  ./hints.lua -do rankpom1 | sort -n -k 3
  630  ./hints.lua -do rankpom | sort -n -k 3
  631  ./hints.lua -do rankpom | sort -n -k 3
  632  ./hints.lua -do rankcoc | sort -n -k 3
  633  ./hints.lua -do rankx4 | sort -n -k 3
  634  ./hints.lua -do rankx4 | sort -n -k 2
  635  ./hints.lua -s 10 -do rankx4 | sort -n -k 2
  636  ./hints.lua -s 8 -do rankx4 | sort -n -k 2
  637  ./hints.lua -s 8 -do rankx4 | sort -n -k 4
  638  cd
  639  cd Dropbox/2021
  640  cd Dropbox
  641  ls
  642  cd 21
  643  ls
  644  cd icse21/
  645  ls
  646  fmt 659-rebuttal.txt 
  647  fmt 659-rebuttal.txt  > a
  648  mv a 659-rebuttal.txt 
  649  cat 659-rebuttal.txt 
  650  wc *rebut*
  651  less 659-rebuttal.txt 
  652  lua
  653  cd
  654  cd rezons
  655  cd src
  656  lua hints.lua -do rankauto
  657  lua hints.lua 
  658  lua hints.lua -do optimize
  659  lua hints.lua -do search
  660  lua hints.lua -do auto93
  661  lua hints.lua -t sway -do auto93
  662  lua hints.lua -t sway -do help
  663  ls ../data
  664  lshead ../data/auto93.csv 
  665  head ../data/auto93.csv 
  666  cat ../data/pom.csv
  667  cat ../data/pom.csv 
  668  cat ../data/pom.csv | head
  669  ls
  670  ./hints.lua -t sway -do optimize
  671  history
  672  ./hints.lua -do rankpom | sort -n -k 3
  673  ./hints.lua -f ../data/pom3.csv  -do optimize | sort -n -k 3
  674  ls ../data/pom.csv 
  675  ./hints.lua -f ../data/pom3.csv  -do optimize 
  676  git pull
  677  history
  678  lua hints.lua -s 4  -do demo1 | sort -k 2
  679  lua hints.lua -t sway -do auto93
  680  lua hints.lua -t sway -do optimize
  681  vi hints.lua 
  682  lua hints.lua -t sway -do search
  683  lua hints.lua -t random -do search
  684  lua hints.lua -t sway -do search | sort -n -k 2
  685  lua hints.lua -t random -do search | sort -n -k 2
  686  lua hints.lua -t random -do search | sort -n -k 3
  687  lua hints.lua -t random -s 5 -do search | sort -n -k 3
  688  lua hints.lua -t random -s 6 -do search | sort -n -k 3
  689  lua hints.lua -t random -s 3 -do search | sort -n -k 3
  690  lua hints.lua -t random -s 3 -f ../data/pom3.csv -do search | sort -n -k 3
  691  lua hints.lua -t random -s 3 -f ../data/pom.csv -do search | sort -n -k 3
  692  lua hints.lua -t random -s 3 -f ../data/pom.csv -do search | sort -n -k 4
  693  lua hints.lua -t random -s 3 -f ../data/pom.csv -do search | sort -n -k 3
  694  lua hints.lua -t sway -s 3 -f ../data/pom.csv -do search | sort -n -k 3
  695  lua hints.lua -t sway -s 10 -f ../data/pom.csv -do search | sort -n -k 3
  696  lua hints.lua -t sway -s 20 -f ../data/pom.csv -do search | sort -n -k 3
  697  ./hints.lua
  698  lua hints.lua -t sway -e .25 -f ../data/pom.csv -do search | sort -n -k 3
  699  lua hints.lua -t sway -e .1 -f ../data/pom.csv -do search | sort -n -k 3
  700  lua hints.lua -t sway -e .0.5 -f ../data/pom.csv -do search | sort -n -k 3
  701  lua hints.lua -t sway -e .05 -f ../data/pom.csv -do search | sort -n -k 3
  702  bat hints.lua 
  703  lua hints.lua -t sway -e .05 -f ../data/pom.csv -do search | sort -n -k 3
  704  gp
  705  history > Makefile
